version: '3.8'
services:
  # Selenium Hub (main control unit)
  selenium-hub:
    image: selenium/hub
#    container_name: selenium-hub
    ports:
      - "4442-4444:4442-4444"   # Expose the hub's port for connection
    networks:
      - grid

  # Chrome Node (to run tests on Chrome)
  node-chrome:
    image: selenium/node-chrome
#    container_name: selenium-node-chrome
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - HUB_HOST=selenium-hub  # Link to the hub
#      - HUB_PORT=4444
#    volumes:
#      - /dev/shm:/dev/shm  # To prevent Chrome from crashing due to insufficient memory
#    depends_on:
#      - selenium-hub
    networks:
      - grid

  # Firefox Node (to run tests on Firefox)
  node-firefox:
    image: selenium/node-firefox
#    container_name: selenium-node-firefox
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - HUB_HOST=selenium-hub  # Link to the hub
#      - HUB_PORT=4444
#    volumes:
#      - /dev/shm:/dev/shm  # To prevent Firefox from crashing due to insufficient memory
#    depends_on:
#      - selenium-hub
    networks:
      - grid

networks:
  grid:
    driver: bridge
